server:
  port: 8082

spring:
  application:
    name: user-service

  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}
      port: 27017
      auto-index-creation: true
      connection-pool:
        max-size: 50
        min-size: 10
        max-wait-time: 2000

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
